<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'code' => '100001',
                'name' => 'Mega Construction Corp',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Makati',
                'suburb_barangay' => 'Poblacion',
                'postal_code' => '1200',
                'address_line_1' => '123 Ayala Avenue',
                'address_line_2' => 'Tower A, 20th Floor',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'John Smith', 'email' => 'john@megaconstruction.ph', 'phone' => '+63 917 111 2222'],
                    ['name' => 'Sarah Johnson', 'email' => 'sarah@megaconstruction.ph', 'phone' => '+63 918 222 3333'],
                ],
                'credit_amount' => 2000000.00,
                'status' => 'active',
            ],
            [
                'code' => '100002',
                'name' => 'Prime Builders Inc',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Quezon City',
                'suburb_barangay' => 'Commonwealth',
                'postal_code' => '1100',
                'address_line_1' => '456 Commonwealth Avenue',
                'address_line_2' => null,
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Michael Chen', 'email' => 'michael@primebuilders.ph', 'phone' => '+63 919 333 4444'],
                ],
                'credit_amount' => 1500000.00,
                'status' => 'active',
            ],
            [
                'code' => '100003',
                'name' => 'Urban Development Partners',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Taguig',
                'suburb_barangay' => 'Fort Bonifacio',
                'postal_code' => '1630',
                'address_line_1' => '789 BGC Drive',
                'address_line_2' => 'Unit 1502',
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'David Lee', 'email' => 'david@urbandev.ph', 'phone' => '+63 920 444 5555'],
                    ['name' => 'Emma Wilson', 'email' => 'emma@urbandev.ph', 'phone' => '+63 921 555 6666'],
                    ['name' => 'James Brown', 'email' => 'james@urbandev.ph', 'phone' => '+63 922 666 7777'],
                ],
                'credit_amount' => 3000000.00,
                'status' => 'active',
            ],
            [
                'code' => '100004',
                'name' => 'Skyline Properties',
                'country' => 'Philippines',
                'state_province' => 'Cavite',
                'city' => 'Bacoor',
                'suburb_barangay' => 'Molino',
                'postal_code' => '4102',
                'address_line_1' => '321 Molino Boulevard',
                'address_line_2' => 'Building B',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Robert Garcia', 'email' => 'robert@skylineproperties.ph', 'phone' => '+63 923 777 8888'],
                ],
                'credit_amount' => 1800000.00,
                'status' => 'active',
            ],
            [
                'code' => '100005',
                'name' => 'Heritage Homes Development',
                'country' => 'Philippines',
                'state_province' => 'Laguna',
                'city' => 'Santa Rosa',
                'suburb_barangay' => 'Tagapo',
                'postal_code' => '4026',
                'address_line_1' => '654 National Highway',
                'address_line_2' => 'Phase 3',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Lisa Martinez', 'email' => 'lisa@heritagehomes.ph', 'phone' => '+63 924 888 9999'],
                    ['name' => 'Thomas Anderson', 'email' => 'thomas@heritagehomes.ph', 'phone' => '+63 925 999 0000'],
                ],
                'credit_amount' => 2500000.00,
                'status' => 'active',
            ],
            [
                'code' => '100006',
                'name' => 'Coastal Realty Group',
                'country' => 'Philippines',
                'state_province' => 'Batangas',
                'city' => 'Lipa',
                'suburb_barangay' => 'Tambo',
                'postal_code' => '4217',
                'address_line_1' => '987 JP Laurel Highway',
                'address_line_2' => null,
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Jennifer Taylor', 'email' => 'jennifer@coastalrealty.ph', 'phone' => '+63 926 111 2222'],
                ],
                'credit_amount' => 1200000.00,
                'status' => 'active',
            ],
            [
                'code' => '100007',
                'name' => 'Metro Housing Solutions',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Pasig',
                'suburb_barangay' => 'Kapitolyo',
                'postal_code' => '1600',
                'address_line_1' => '246 Ortigas Avenue',
                'address_line_2' => '8th Floor',
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'Christopher White', 'email' => 'christopher@metrohousing.ph', 'phone' => '+63 927 222 3333'],
                    ['name' => 'Amanda Clark', 'email' => 'amanda@metrohousing.ph', 'phone' => '+63 928 333 4444'],
                ],
                'credit_amount' => 2200000.00,
                'status' => 'active',
            ],
            [
                'code' => '100008',
                'name' => 'Provincial Builders Association',
                'country' => 'Philippines',
                'state_province' => 'Pampanga',
                'city' => 'Angeles City',
                'suburb_barangay' => 'Balibago',
                'postal_code' => '2009',
                'address_line_1' => '135 MacArthur Highway',
                'address_line_2' => 'Commercial Center',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Daniel Rodriguez', 'email' => 'daniel@provincialbuilders.ph', 'phone' => '+63 929 444 5555'],
                ],
                'credit_amount' => 1400000.00,
                'status' => 'active',
            ],
            [
                'code' => '100009',
                'name' => 'Summit Construction Group',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'suburb_barangay' => 'Lahug',
                'postal_code' => '6000',
                'address_line_1' => '579 Osmeña Boulevard',
                'address_line_2' => 'Suite 300',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Matthew Harris', 'email' => 'matthew@summitconstruction.ph', 'phone' => '+63 930 555 6666'],
                    ['name' => 'Olivia Martin', 'email' => 'olivia@summitconstruction.ph', 'phone' => '+63 931 666 7777'],
                ],
                'credit_amount' => 1900000.00,
                'status' => 'active',
            ],
            [
                'code' => '100010',
                'name' => 'Landmark Developers Corp',
                'country' => 'Philippines',
                'state_province' => 'Rizal',
                'city' => 'Cainta',
                'suburb_barangay' => 'San Isidro',
                'postal_code' => '1900',
                'address_line_1' => '864 Felix Avenue',
                'address_line_2' => null,
                'payment_terms' => 'COD',
                'contact_persons' => [
                    ['name' => 'Andrew Thompson', 'email' => 'andrew@landmarkdev.ph', 'phone' => '+63 932 777 8888'],
                ],
                'credit_amount' => 0.00,
                'status' => 'active',
            ],
            [
                'code' => '100011',
                'name' => 'Pacific Estates Inc',
                'country' => 'Philippines',
                'state_province' => 'Bulacan',
                'city' => 'Malolos',
                'suburb_barangay' => 'Barasoain',
                'postal_code' => '3000',
                'address_line_1' => '753 McArthur Highway',
                'address_line_2' => 'Main Office',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Sophia Moore', 'email' => 'sophia@pacificestates.ph', 'phone' => '+63 933 888 9999'],
                ],
                'credit_amount' => 1600000.00,
                'status' => 'active',
            ],
            [
                'code' => '100012',
                'name' => 'Green Valley Communities',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Mandaluyong',
                'suburb_barangay' => 'Highway Hills',
                'postal_code' => '1550',
                'address_line_1' => '951 Shaw Boulevard',
                'address_line_2' => '12th Floor',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'William Jackson', 'email' => 'william@greenvalley.ph', 'phone' => '+63 934 999 0000'],
                    ['name' => 'Isabella Young', 'email' => 'isabella@greenvalley.ph', 'phone' => '+63 935 111 2222'],
                ],
                'credit_amount' => 2100000.00,
                'status' => 'active',
            ],
            [
                'code' => '100013',
                'name' => 'Elite Property Ventures',
                'country' => 'Philippines',
                'state_province' => 'Cavite',
                'city' => 'Dasmarinas',
                'suburb_barangay' => 'Salitran',
                'postal_code' => '4114',
                'address_line_1' => '357 Governor Drive',
                'address_line_2' => 'Block 5',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Joseph King', 'email' => 'joseph@eliteproperty.ph', 'phone' => '+63 936 222 3333'],
                ],
                'credit_amount' => 1300000.00,
                'status' => 'active',
            ],
            [
                'code' => '100014',
                'name' => 'Prestige Homes & Condos',
                'country' => 'Philippines',
                'state_province' => 'Laguna',
                'city' => 'Binan',
                'suburb_barangay' => 'San Antonio',
                'postal_code' => '4024',
                'address_line_1' => '159 Carmona Road',
                'address_line_2' => 'Sales Office',
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'Emily Scott', 'email' => 'emily@prestigehomes.ph', 'phone' => '+63 937 333 4444'],
                    ['name' => 'Ryan Adams', 'email' => 'ryan@prestigehomes.ph', 'phone' => '+63 938 444 5555'],
                ],
                'credit_amount' => 950000.00,
                'status' => 'inactive',
            ],
            [
                'code' => '100015',
                'name' => 'Horizon Real Estate Partners',
                'country' => 'Philippines',
                'state_province' => 'Rizal',
                'city' => 'Antipolo',
                'suburb_barangay' => 'San Roque',
                'postal_code' => '1870',
                'address_line_1' => '741 Sumulong Highway',
                'address_line_2' => 'Lot 22',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Victoria Baker', 'email' => 'victoria@horizonrealestate.ph', 'phone' => '+63 939 555 6666'],
                ],
                'credit_amount' => 1700000.00,
                'status' => 'active',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}
