<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Material;
use App\Models\Uom;
use Illuminate\Database\Seeder;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        $brands = Brand::all();
        $categories = Category::all();
        $uoms = Uom::all();

        $materials = [
            [
                'code' => '300001',
                'name' => 'Steel Rod 12mm',
                'description' => 'High-grade steel rod for construction',
                'weight' => 8.5,
                'length' => 6.0,
                'width' => null,
                'height' => null,
                'volume' => null,
                'min_stock_level' => 100,
                'max_stock_level' => 500,
                'reorder_level' => 150,
                'unit_cost' => 250.00,
                'unit_price' => 350.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300002',
                'name' => 'Cement Portland',
                'description' => '50kg bag Portland cement',
                'weight' => 50.0,
                'length' => null,
                'width' => null,
                'height' => null,
                'volume' => null,
                'min_stock_level' => 200,
                'max_stock_level' => 1000,
                'reorder_level' => 300,
                'unit_cost' => 180.00,
                'unit_price' => 220.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300003',
                'name' => 'Plywood 4x8 ft',
                'description' => 'Marine grade plywood',
                'weight' => 25.0,
                'length' => 8.0,
                'width' => 4.0,
                'height' => 0.75,
                'volume' => 24.0,
                'min_stock_level' => 50,
                'max_stock_level' => 200,
                'reorder_level' => 75,
                'unit_cost' => 650.00,
                'unit_price' => 850.00,
                'status' => 'active',
                'track_serial_number' => true,
                'track_batch_number' => false,
            ],
            [
                'code' => '300004',
                'name' => 'Paint White Latex',
                'description' => '5 gallon white latex paint',
                'weight' => 20.0,
                'length' => null,
                'width' => null,
                'height' => null,
                'volume' => 18.9,
                'min_stock_level' => 30,
                'max_stock_level' => 150,
                'reorder_level' => 50,
                'unit_cost' => 1200.00,
                'unit_price' => 1600.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300005',
                'name' => 'Wire Cable 2.0mm',
                'description' => 'Electrical wire copper cable',
                'weight' => 15.0,
                'length' => 100.0,
                'width' => null,
                'height' => null,
                'volume' => null,
                'min_stock_level' => 80,
                'max_stock_level' => 400,
                'reorder_level' => 120,
                'unit_cost' => 850.00,
                'unit_price' => 1100.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300006',
                'name' => 'Ceramic Tiles 30x30',
                'description' => 'Glazed ceramic floor tiles',
                'weight' => 1.2,
                'length' => 0.3,
                'width' => 0.3,
                'height' => 0.01,
                'volume' => 0.0009,
                'min_stock_level' => 500,
                'max_stock_level' => 2000,
                'reorder_level' => 750,
                'unit_cost' => 45.00,
                'unit_price' => 65.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300007',
                'name' => 'PVC Pipe 1 inch',
                'description' => 'Schedule 40 PVC pipe',
                'weight' => 2.5,
                'length' => 3.0,
                'width' => null,
                'height' => null,
                'volume' => null,
                'min_stock_level' => 150,
                'max_stock_level' => 600,
                'reorder_level' => 200,
                'unit_cost' => 120.00,
                'unit_price' => 165.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => false,
            ],
            [
                'code' => '300008',
                'name' => 'Gravel 3/4 inch',
                'description' => 'Crushed stone aggregate',
                'weight' => 1500.0,
                'length' => null,
                'width' => null,
                'height' => null,
                'volume' => 1.0,
                'min_stock_level' => 10,
                'max_stock_level' => 50,
                'reorder_level' => 15,
                'unit_cost' => 800.00,
                'unit_price' => 1000.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => false,
            ],
            [
                'code' => '300009',
                'name' => 'Aluminum Sheet 4x8',
                'description' => '0.5mm aluminum sheet',
                'weight' => 18.0,
                'length' => 8.0,
                'width' => 4.0,
                'height' => 0.0005,
                'volume' => 0.016,
                'min_stock_level' => 40,
                'max_stock_level' => 180,
                'reorder_level' => 60,
                'unit_cost' => 1850.00,
                'unit_price' => 2400.00,
                'status' => 'active',
                'track_serial_number' => true,
                'track_batch_number' => false,
            ],
            [
                'code' => '300010',
                'name' => 'Glass Panel 6mm',
                'description' => 'Tempered glass panel',
                'weight' => 15.0,
                'length' => 1.2,
                'width' => 0.9,
                'height' => 0.006,
                'volume' => 0.00648,
                'min_stock_level' => 25,
                'max_stock_level' => 100,
                'reorder_level' => 35,
                'unit_cost' => 1200.00,
                'unit_price' => 1650.00,
                'status' => 'active',
                'track_serial_number' => true,
                'track_batch_number' => false,
            ],
            [
                'code' => '300011',
                'name' => 'Concrete Blocks 6x8x16',
                'description' => 'Hollow concrete masonry unit',
                'weight' => 16.0,
                'length' => 0.4,
                'width' => 0.2,
                'height' => 0.15,
                'volume' => 0.012,
                'min_stock_level' => 300,
                'max_stock_level' => 1500,
                'reorder_level' => 450,
                'unit_cost' => 28.00,
                'unit_price' => 38.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => false,
            ],
            [
                'code' => '300012',
                'name' => 'Sand Fine',
                'description' => 'Washed fine sand for masonry',
                'weight' => 1600.0,
                'length' => null,
                'width' => null,
                'height' => null,
                'volume' => 1.0,
                'min_stock_level' => 15,
                'max_stock_level' => 60,
                'reorder_level' => 20,
                'unit_cost' => 600.00,
                'unit_price' => 780.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => false,
            ],
            [
                'code' => '300013',
                'name' => 'Nails 3 inch',
                'description' => 'Common steel nails',
                'weight' => 25.0,
                'length' => 0.076,
                'width' => null,
                'height' => null,
                'volume' => null,
                'min_stock_level' => 50,
                'max_stock_level' => 250,
                'reorder_level' => 80,
                'unit_cost' => 180.00,
                'unit_price' => 240.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => false,
            ],
            [
                'code' => '300014',
                'name' => 'Lumber 2x4x10',
                'description' => 'Pine lumber dimension',
                'weight' => 12.0,
                'length' => 3.0,
                'width' => 0.1,
                'height' => 0.05,
                'volume' => 0.015,
                'min_stock_level' => 100,
                'max_stock_level' => 500,
                'reorder_level' => 150,
                'unit_cost' => 245.00,
                'unit_price' => 320.00,
                'status' => 'active',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
            [
                'code' => '300015',
                'name' => 'Insulation Roll',
                'description' => 'Fiberglass insulation R-13',
                'weight' => 8.0,
                'length' => 4.5,
                'width' => 0.4,
                'height' => 0.09,
                'volume' => 0.162,
                'min_stock_level' => 60,
                'max_stock_level' => 300,
                'reorder_level' => 90,
                'unit_cost' => 380.00,
                'unit_price' => 520.00,
                'status' => 'inactive',
                'track_serial_number' => false,
                'track_batch_number' => true,
            ],
        ];

        foreach ($materials as $material) {
            Material::create([
                ...$material,
                'brand_id' => $brands->random()->id ?? null,
                'category_id' => $categories->random()->id ?? null,
                'uom_id' => $uoms->random()->id ?? null,
            ]);
        }
    }
}
