<?php

namespace Database\Seeders;

use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = [
            [
                'code' => '200001',
                'name' => 'ABC Steel Supply Co.',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Quezon City',
                'suburb_barangay' => 'Commonwealth',
                'postal_code' => '1100',
                'address_line_1' => '123 Industrial Avenue',
                'address_line_2' => 'Brgy. Commonwealth',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Juan Dela Cruz', 'email' => 'juan@abcsteel.com', 'phone' => '+63 917 123 4567'],
                    ['name' => 'Maria Santos', 'email' => 'maria@abcsteel.com', 'phone' => '+63 918 234 5678'],
                ],
                'credit_amount' => 500000.00,
                'status' => 'active',
            ],
            [
                'code' => '200002',
                'name' => 'BuildMart International',
                'country' => 'Philippines',
                'state_province' => 'Cavite',
                'city' => 'Bacoor',
                'suburb_barangay' => 'Molino',
                'postal_code' => '4102',
                'address_line_1' => '456 Construction Road',
                'address_line_2' => null,
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Pedro Reyes', 'email' => 'pedro@buildmart.ph', 'phone' => '+63 919 345 6789'],
                ],
                'credit_amount' => 750000.00,
                'status' => 'active',
            ],
            [
                'code' => '200003',
                'name' => 'Global Hardware Trading',
                'country' => 'Philippines',
                'state_province' => 'Rizal',
                'city' => 'Cainta',
                'suburb_barangay' => 'San Isidro',
                'postal_code' => '1900',
                'address_line_1' => '789 Commerce Street',
                'address_line_2' => 'Unit 5B',
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'Anna Cruz', 'email' => 'anna@globalhardware.com', 'phone' => '+63 920 456 7890'],
                    ['name' => 'Carlos Mendoza', 'email' => 'carlos@globalhardware.com', 'phone' => '+63 921 567 8901'],
                    ['name' => 'Rosa Garcia', 'email' => 'rosa@globalhardware.com', 'phone' => '+63 922 678 9012'],
                ],
                'credit_amount' => 1000000.00,
                'status' => 'active',
            ],
            [
                'code' => '200004',
                'name' => 'Pacific Cement Corp',
                'country' => 'Philippines',
                'state_province' => 'Bulacan',
                'city' => 'Marilao',
                'suburb_barangay' => 'Ibayo',
                'postal_code' => '3019',
                'address_line_1' => '321 Industry Park',
                'address_line_2' => 'PEZA Zone',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Roberto Tan', 'email' => 'roberto@pacificcement.ph', 'phone' => '+63 923 789 0123'],
                ],
                'credit_amount' => 600000.00,
                'status' => 'active',
            ],
            [
                'code' => '200005',
                'name' => 'Eastern Lumber Mills',
                'country' => 'Philippines',
                'state_province' => 'Laguna',
                'city' => 'Calamba',
                'suburb_barangay' => 'Batino',
                'postal_code' => '4027',
                'address_line_1' => '654 Forest Road',
                'address_line_2' => 'Batino Area',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Linda Ramos', 'email' => 'linda@easternlumber.ph', 'phone' => '+63 924 890 1234'],
                    ['name' => 'Jose Rivera', 'email' => 'jose@easternlumber.ph', 'phone' => '+63 925 901 2345'],
                ],
                'credit_amount' => 450000.00,
                'status' => 'active',
            ],
            [
                'code' => '200006',
                'name' => 'Premium Paints Inc',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Makati',
                'suburb_barangay' => 'Poblacion',
                'postal_code' => '1200',
                'address_line_1' => '987 Corporate Avenue',
                'address_line_2' => '15th Floor',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Michelle Lee', 'email' => 'michelle@premiumpaints.ph', 'phone' => '+63 926 012 3456'],
                ],
                'credit_amount' => 350000.00,
                'status' => 'active',
            ],
            [
                'code' => '200007',
                'name' => 'Metro Electrical Supply',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Mandaluyong',
                'suburb_barangay' => 'Highway Hills',
                'postal_code' => '1550',
                'address_line_1' => '246 Electric Street',
                'address_line_2' => null,
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'Daniel Torres', 'email' => 'daniel@metroelectrical.ph', 'phone' => '+63 927 123 4567'],
                    ['name' => 'Grace Flores', 'email' => 'grace@metroelectrical.ph', 'phone' => '+63 928 234 5678'],
                ],
                'credit_amount' => 800000.00,
                'status' => 'active',
            ],
            [
                'code' => '200008',
                'name' => 'Ceramic Tiles Pro',
                'country' => 'Philippines',
                'state_province' => 'Pampanga',
                'city' => 'Angeles City',
                'suburb_barangay' => 'Balibago',
                'postal_code' => '2009',
                'address_line_1' => '135 Tiles Boulevard',
                'address_line_2' => 'Phase 2',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Samuel Cruz', 'email' => 'samuel@ceramicpro.ph', 'phone' => '+63 929 345 6789'],
                ],
                'credit_amount' => 420000.00,
                'status' => 'active',
            ],
            [
                'code' => '200009',
                'name' => 'Supreme Plumbing Supplies',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'suburb_barangay' => 'Lahug',
                'postal_code' => '6000',
                'address_line_1' => '579 Plumbing Way',
                'address_line_2' => 'Warehouse 3',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Eduardo Bautista', 'email' => 'eduardo@supremeplumbing.ph', 'phone' => '+63 930 456 7890'],
                    ['name' => 'Teresa Gonzales', 'email' => 'teresa@supremeplumbing.ph', 'phone' => '+63 931 567 8901'],
                ],
                'credit_amount' => 550000.00,
                'status' => 'active',
            ],
            [
                'code' => '200010',
                'name' => 'Aggregate Solutions Corp',
                'country' => 'Philippines',
                'state_province' => 'Batangas',
                'city' => 'Lipa',
                'suburb_barangay' => 'Tambo',
                'postal_code' => '4217',
                'address_line_1' => '864 Quarry Road',
                'address_line_2' => null,
                'payment_terms' => 'COD',
                'contact_persons' => [
                    ['name' => 'Ramon Silva', 'email' => 'ramon@aggregatesolutions.ph', 'phone' => '+63 932 678 9012'],
                ],
                'credit_amount' => 0.00,
                'status' => 'active',
            ],
            [
                'code' => '200011',
                'name' => 'Metalworks Trading',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Pasig',
                'suburb_barangay' => 'Kapitolyo',
                'postal_code' => '1600',
                'address_line_1' => '753 Metal Avenue',
                'address_line_2' => 'Building A',
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Victor Diaz', 'email' => 'victor@metalworks.ph', 'phone' => '+63 933 789 0123'],
                ],
                'credit_amount' => 650000.00,
                'status' => 'active',
            ],
            [
                'code' => '200012',
                'name' => 'Glass & Glazing Co.',
                'country' => 'Philippines',
                'state_province' => 'Metro Manila',
                'city' => 'Taguig',
                'suburb_barangay' => 'Fort Bonifacio',
                'postal_code' => '1630',
                'address_line_1' => '951 BGC High Street',
                'address_line_2' => 'Unit 201',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Patricia Cruz', 'email' => 'patricia@glassglazing.ph', 'phone' => '+63 934 890 1234'],
                    ['name' => 'Mark Santos', 'email' => 'mark@glassglazing.ph', 'phone' => '+63 935 901 2345'],
                ],
                'credit_amount' => 500000.00,
                'status' => 'active',
            ],
            [
                'code' => '200013',
                'name' => 'Block & Brick Supplies',
                'country' => 'Philippines',
                'state_province' => 'Rizal',
                'city' => 'Antipolo',
                'suburb_barangay' => 'San Roque',
                'postal_code' => '1870',
                'address_line_1' => '357 Masonry Street',
                'address_line_2' => null,
                'payment_terms' => 'Net 30',
                'contact_persons' => [
                    ['name' => 'Angela Reyes', 'email' => 'angela@blockbrick.ph', 'phone' => '+63 936 012 3456'],
                ],
                'credit_amount' => 380000.00,
                'status' => 'active',
            ],
            [
                'code' => '200014',
                'name' => 'Fasteners Warehouse',
                'country' => 'Philippines',
                'state_province' => 'Cavite',
                'city' => 'Dasmarinas',
                'suburb_barangay' => 'Salitran',
                'postal_code' => '4114',
                'address_line_1' => '159 Hardware Highway',
                'address_line_2' => 'Bay 7',
                'payment_terms' => 'Net 60',
                'contact_persons' => [
                    ['name' => 'Benjamin Tan', 'email' => 'benjamin@fasteners.ph', 'phone' => '+63 937 123 4567'],
                    ['name' => 'Diana Lopez', 'email' => 'diana@fasteners.ph', 'phone' => '+63 938 234 5678'],
                ],
                'credit_amount' => 280000.00,
                'status' => 'inactive',
            ],
            [
                'code' => '200015',
                'name' => 'Insulation Pro Supplies',
                'country' => 'Philippines',
                'state_province' => 'Laguna',
                'city' => 'Binan',
                'suburb_barangay' => 'San Antonio',
                'postal_code' => '4024',
                'address_line_1' => '741 Industrial Park Road',
                'address_line_2' => 'Lot 15',
                'payment_terms' => 'Net 45',
                'contact_persons' => [
                    ['name' => 'Christina Ramos', 'email' => 'christina@insulationpro.ph', 'phone' => '+63 939 345 6789'],
                ],
                'credit_amount' => 320000.00,
                'status' => 'active',
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::create($vendor);
        }
    }
}
